# -*- coding: utf-8 -*-
from . import hr_employee
from . import hr_org_structure
from . import hr_contract
from . import hr_contract_history
from . import res_company
from . import res_config_settings
from . import dm_hr_expiry_alert
from . import dm_hr_allowance_type
from . import dm_hr_contract_allowance
from . import dm_hr_employee_allowance
from . import dm_hr_insurance_provider
from . import dm_hr_insurance_policy
from . import dm_hr_social_insurance_scheme
from . import dm_hr_social_insurance_rate
from . import dm_hr_employee_dependent
from . import dm_hr_document
from . import dm_hr_service_request
from . import dm_hr_service_request_type
from . import dm_hr_service_center
from . import dm_hr_approval_policy
from . import dm_hr_shift
from . import dm_hr_phase2
from . import dm_hr_phase3
from . import dm_hr_leave_finance
from . import dm_hr_attendance
